# Generated by tools/build_portable.py from the tested ComfyUI API implementation.
# Credential values are never included. This snapshot needs no ComfyUI, numpy or torch.
import base64, csv, datetime, hashlib, io, json, os, shutil, time, uuid, zipfile
from pathlib import Path
from urllib.parse import urlsplit, urlunsplit
import requests
from filelock import FileLock, Timeout
from PIL import Image as PILImage
API_BASE = 'https://api.openai.com/v1'
KEY_FILE = Path(__file__).parent / 'api_key.txt'
COST_LOG = Path(__file__).parent / 'results/fabric_cost_log.csv'
PRICING_URL = 'https://developers.openai.com/api/docs/pricing'
PRICING_DATE = '2026-09-09'
def _decode_image(raw):
    with PILImage.open(io.BytesIO(raw)) as image:
        image.load()

MODELS = ['gpt-image-2', 'gpt-image-2.5-sunburst-2026-09-08', 'gpt-image-2.5-sunburst', 'gpt-image-2.5-flare', 'gpt-image-1.5', 'gpt-image-1']
SIZES = ['auto', '1024x1024', '1024x1536', '1536x1024', '2048x2048', '2048x1152', '1152x2048', '3840x2160', '2160x3840', 'Custom']
def estimate_usage_cost(model, usage):
    """Standard USD rates; missing usage is unknown, never zero consumption."""
    result = dict(currency='USD', usd_min=None, usd_max=None, pricing_url=PRICING_URL, pricing_date=PRICING_DATE, assumptions=[])
    if model == 'gpt-image-2' or model.startswith(('gpt-image-2.5-sunburst', 'gpt-image-2.5-flare')):
        rates = dict(text_input=5, image_input=8, cached_text=1.25, cached_image=2, image_output=30, text_output=0)
    elif model == 'gpt-image-1.5':
        rates = dict(text_input=5, image_input=8, cached_text=1.25, cached_image=2, image_output=32, text_output=10)
    elif model == 'gpt-image-1':
        rates = dict(text_input=5, image_input=10, cached_text=1.25, cached_image=2.5, image_output=40, text_output=0)
    else:
        result['status'] = 'unknown_model'
        return result
    result['rates_per_million'] = rates
    if not usage:
        result['status'] = 'usage_unavailable'
        return result
    detail = usage.get('input_tokens_details', {}) or {}
    out = usage.get('output_tokens_details', {}) or {}
    required = [usage.get('input_tokens'), usage.get('output_tokens'), detail.get('text_tokens'), detail.get('image_tokens')]
    if any((not isinstance(v, int) or isinstance(v, bool) or v < 0 for v in required)):
        result['status'] = 'incomplete_usage'
        return result
    total_in, total_out, text_in, image_in = required
    if text_in + image_in != total_in:
        result['status'] = 'inconsistent_usage'
        return result
    if not out:
        if model == 'gpt-image-1.5':
            result['status'] = 'incomplete_usage'
            return result
        out = dict(image_tokens=total_out, text_tokens=0)
        result['assumptions'].append('Images API 输出 token 全部按图像计价')
    image_out, text_out = (out.get('image_tokens', 0), out.get('text_tokens', 0))
    if any((not isinstance(v, int) or isinstance(v, bool) or v < 0 for v in (image_out, text_out))) or image_out + text_out != total_out:
        result['status'] = 'inconsistent_usage'
        return result
    if text_out and rates['text_output'] == 0:
        result['status'] = 'unsupported_text_output'
        return result
    cached = detail.get('cached_tokens', usage.get('cached_tokens'))
    if cached is None:
        cached = 0
        result['assumptions'].append('接口未报告缓存 token，按未缓存输入估算；若账单有缓存优惠，实际费用更低')
    if not isinstance(cached, int) or isinstance(cached, bool) or (not 0 <= cached <= total_in):
        result['status'] = 'inconsistent_usage'
        return result
    cached_detail = detail.get('cached_tokens_details', {}) or {}
    if cached_detail and all((k in cached_detail for k in ('text_tokens', 'image_tokens'))):
        ct, ci = (cached_detail['text_tokens'], cached_detail['image_tokens'])
        if any((not isinstance(v, int) or isinstance(v, bool) or v < 0 for v in (ct, ci))) or ct + ci != cached or ct > text_in or (ci > image_in):
            result['status'] = 'inconsistent_usage'
            return result
        allocations = [(ct, ci)]
    else:
        allocations = [(ct, cached - ct) for ct in (max(0, cached - image_in), min(cached, text_in))]
        if cached:
            result['assumptions'].append('缓存 token 未按模态拆分，按可行分配估算区间')
    costs = [((text_in - ct) * rates['text_input'] + ct * rates['cached_text'] + (image_in - ci) * rates['image_input'] + ci * rates['cached_image'] + image_out * rates['image_output'] + text_out * rates['text_output']) / 1000000 for ct, ci in allocations]
    result.update(status='estimated', usd_min=round(min(costs), 8), usd_max=round(max(costs), 8))
    return result

def _cost_text(cost):
    if cost.get('status') == 'relay_pricing_unknown':
        return '中转站价格未配置，费用未知；以该站账单为准'
    if cost['usd_min'] is None:
        return '用量或拆分不足，费用未知'
    lo, hi = (cost['usd_min'], cost['usd_max'])
    return f'估算 ${lo:.5f}' if lo == hi else f'估算 ${lo:.5f}–${hi:.5f}'

def normalize_api_base(value):
    value = (value or API_BASE).strip().rstrip('/')
    parts = urlsplit(value)
    if parts.username or parts.password or parts.query or parts.fragment:
        raise ValueError('接口地址中不要包含密钥、账号、查询参数或 # 片段；密钥单独填写。')
    if not parts.hostname or any((ch.isspace() for ch in value)):
        raise ValueError('请填写完整 API 地址，例如 https://api.openai.com/v1。')
    if parts.scheme != 'https' and (not (parts.scheme == 'http' and parts.hostname in ('localhost', '127.0.0.1', '::1'))):
        raise ValueError('远程 API 地址需要 HTTPS；本机服务可使用 HTTP。')
    path = parts.path.rstrip('/')
    for endpoint in ('/images/generations', '/images/edits'):
        if path.endswith(endpoint):
            path = path[:-len(endpoint)]
            break
    path = path or '/v1'
    return urlunsplit((parts.scheme.lower(), parts.netloc.lower(), path, '', ''))

def endpoint_cost(model, usage, api_base_url):
    if api_base_url == API_BASE:
        return estimate_usage_cost(model, usage)
    return dict(currency='USD', status='relay_pricing_unknown', usd_min=None, usd_max=None, pricing_url=None, pricing_date=None, assumptions=['中转站收费规则未知，不使用官方单价估算'])

def request_key(inline_key, api_key_file, api_base_url):
    if inline_key and inline_key.strip():
        return inline_key.strip()
    if api_key_file and api_key_file.strip():
        path = Path(api_key_file.strip()).expanduser()
        if not path.is_absolute():
            path = KEY_FILE.parent / path
        if not path.is_file():
            raise ValueError('找不到指定的密钥文件。请检查路径。')
        return path.read_text(encoding='utf-8-sig').strip()
    if api_base_url != API_BASE:
        raise ValueError('中转站需要填写对应 API Key 或密钥文件；不会自动把官方 Key 发给中转站。')
    return resolve_api_key()

def download_image(url):
    parts = urlsplit(url)
    if parts.scheme != 'https' or not parts.hostname or parts.username or parts.password:
        raise ValueError('接口返回的图片下载地址需要是无账号密码的 HTTPS URL。')
    with requests.get(url, headers={}, timeout=(20, 120), stream=True, allow_redirects=False) as response:
        if response.status_code != 200:
            raise RuntimeError(f'图片下载 HTTP {response.status_code}；未重新生图。')
        chunks, size = ([], 0)
        for chunk in response.iter_content(65536):
            size += len(chunk)
            if size > 50 * 1024 * 1024:
                raise ValueError('返回图片超过 50 MB，下载已停止；未重新生图。')
            chunks.append(chunk)
        return b''.join(chunks)

def _repair_csv_header(path, fieldnames):
    if not path.exists() or not path.stat().st_size:
        return
    with path.open(encoding='utf-8-sig', newline='') as source:
        rows = list(csv.reader(source))
    if rows[0] == fieldnames:
        return
    backup = path.with_name(path.stem + '.before-usage-fix.csv')
    if not backup.exists():
        shutil.copy2(path, backup)
    repaired = []
    for values in rows[1:]:
        header = rows[0]
        if 'usage' not in header and len(values) == len(header) + 1:
            header = header[:-1] + ['usage', header[-1]]
        if len(values) != len(header):
            raise ValueError('旧 CSV 列数不一致，已备份原始日志，请检查。')
        old = dict(zip(header, values))
        row = {k: old.get(k, '') for k in fieldnames}
        usage = json.loads(old['usage']) if old.get('usage') else None
        api_base_url = old.get('api_base_url') or API_BASE
        cost = endpoint_cost(old.get('model', ''), usage, api_base_url)
        cache_hit = old.get('status') == 'cache_hit' or old.get('cache_hit') in (True, 'True', 'true', '1')
        if cache_hit:
            cost.update(usd_min=0.0, usd_max=0.0)
        _fill_usage_columns(row, usage)
        row.update(usd_estimate_min=cost['usd_min'], usd_estimate_max=cost['usd_max'], pricing_date=cost.get('pricing_date'), cache_hit=cache_hit)
        if 'api_base_url' in row:
            row.update(api_base_url=api_base_url, pricing_source='OpenAI published rates' if api_base_url == API_BASE else 'relay price unknown')
        repaired.append(row)
    temp = path.with_suffix('.csv.tmp')
    with temp.open('w', encoding='utf-8-sig', newline='') as out:
        writer = csv.DictWriter(out, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(repaired)
    os.replace(temp, path)

def _fill_usage_columns(row, usage):
    usage = usage or {}
    detail = usage.get('input_tokens_details', {}) or {}
    row.update(input_tokens=usage.get('input_tokens', ''), input_text_tokens=detail.get('text_tokens', ''), input_image_tokens=detail.get('image_tokens', ''), output_tokens=usage.get('output_tokens', ''), total_tokens=usage.get('total_tokens', ''), cached_tokens=detail.get('cached_tokens', usage.get('cached_tokens', '')))

def resolve_api_key():
    key = os.environ.get('OPENAI_API_KEY', '').strip()
    if not key and KEY_FILE.exists():
        key = KEY_FILE.read_text(encoding='utf-8').strip()
    return key

def validate_size(model, size, custom_width, custom_height):
    if model not in MODELS or size not in SIZES:
        raise ValueError('模型或尺寸无效，请从下拉框选择。')
    if size == 'auto':
        return size
    if model in ('gpt-image-1', 'gpt-image-1.5'):
        if size not in ('1024x1024', '1024x1536', '1536x1024'):
            raise ValueError('此旧模型仅支持 1024x1024 / 1024x1536 / 1536x1024。')
        return size
    w, h = (custom_width, custom_height) if size == 'Custom' else map(int, size.split('x'))
    if min(w, h) <= 0 or w % 16 or h % 16:
        raise ValueError('宽高必须为正数且是 16 的倍数。')
    if max(w, h) > 3840 or max(w, h) / min(w, h) > 3:
        raise ValueError('最长边不得超过 3840，长宽比不得超过 3:1。')
    if not 655360 <= w * h <= 8294400:
        raise ValueError('总像素需在 655,360 至 8,294,400 之间。')
    return f'{w}x{h}'

def _log_request(status, request, ref_count, usage=None, http_status=0, error='', request_id='', request_hash='', elapsed_seconds=None, original_usage=None, api_base_url=API_BASE):
    cache_hit = status == 'cache_hit'
    cost = endpoint_cost(request['model'], usage, api_base_url)
    if cache_hit:
        cost.update(status='local_cache', usd_min=0.0, usd_max=0.0, assumptions=[])
    row = dict(time=datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S'), status=status, model=request['model'], quality=request['quality'], size=request['size'], n=request['n'], ref_images=ref_count, est_usd_min='', est_usd_max='', http_status=http_status, key_origin='BYOK', prompt_len=len(request['prompt']), usage=json.dumps(usage, ensure_ascii=False) if usage else '', error=error)
    _fill_usage_columns(row, usage)
    row.update(cached_tokens=row['cached_tokens'], usd_estimate_min=cost['usd_min'], usd_estimate_max=cost['usd_max'], pricing_date=cost.get('pricing_date'), request_id=request_id, request_hash=request_hash, elapsed_seconds=elapsed_seconds, cache_hit=cache_hit, api_base_url=api_base_url, pricing_source='OpenAI published rates' if api_base_url == API_BASE else 'relay price unknown')
    event = dict(schema=1, time=row['time'], status=status, model=request['model'], quality=request['quality'], size=request['size'], n=request['n'], ref_images=ref_count, request_id=request_id, request_hash=request_hash, elapsed_seconds=elapsed_seconds, cache_hit=cache_hit, http_status=http_status, usage=usage, original_usage=original_usage, cost=cost, error=error, api_base_url=api_base_url)
    try:
        COST_LOG.parent.mkdir(parents=True, exist_ok=True)
        with FileLock(str(COST_LOG) + '.lock', timeout=10):
            with COST_LOG.with_name('fabric_usage_log.jsonl').open('a', encoding='utf-8') as out:
                out.write(json.dumps(event, ensure_ascii=False) + '\n')
            _repair_csv_header(COST_LOG, list(row))
            new = not COST_LOG.exists() or not COST_LOG.stat().st_size
            with COST_LOG.open('a', newline='', encoding='utf-8-sig') as out:
                writer = csv.DictWriter(out, fieldnames=list(row))
                if new:
                    writer.writeheader()
                writer.writerow(row)
    except (OSError, Timeout, ValueError) as exc:
        print(f'[fabric-cost] 日志写入失败: {type(exc).__name__}')

def _save_cache(path, images, metadata):
    metadata = {**metadata, 'output_sha256': [hashlib.sha256(x).hexdigest() for x in images]}
    temp = path.with_name(path.name + '.' + uuid.uuid4().hex + '.tmp')
    try:
        with zipfile.ZipFile(temp, 'w', compression=zipfile.ZIP_STORED) as archive:
            archive.writestr('manifest.json', json.dumps(metadata, ensure_ascii=False, indent=2))
            for i, raw in enumerate(images):
                archive.writestr(f'{i}.png', raw)
        os.replace(temp, path)
    finally:
        temp.unlink(missing_ok=True)

def _load_cache(path, expected_hash, n):
    try:
        with zipfile.ZipFile(path) as archive:
            metadata = json.loads(archive.read('manifest.json'))
            if metadata['request_hash'] != expected_hash or len(metadata['output_sha256']) != n:
                raise ValueError('缓存记录不匹配')
            images = [archive.read(f'{i}.png') for i in range(n)]
            if [hashlib.sha256(x).hexdigest() for x in images] != metadata['output_sha256']:
                raise ValueError('缓存图片校验失败')
            for raw in images:
                _decode_image(raw)
            return (images, metadata)
    except (OSError, ValueError, KeyError, zipfile.BadZipFile) as exc:
        raise RuntimeError(f'本地缓存损坏，未调用 API。请将 cache_mode 改为 refresh 后手动重试。文件: {path.name}') from exc

class FabricGPTImage2:

    def _request(self, request, payloads, mask_bytes, openai_api_key, manifest, request_hash, api_key_file=''):
        api_base_url = manifest.get('api_base_url', API_BASE)
        key = request_key(openai_api_key, api_key_file, api_base_url)
        if not key:
            raise ValueError('未找到 OpenAI Key，请在 api_key.txt 或环境变量中配置。')
        headers = {'Authorization': f'Bearer {key}'}
        endpoint = 'images/edits' if payloads else 'images/generations'
        started = time.perf_counter()
        try:
            if payloads:
                field = 'image' if len(payloads) == 1 else 'image[]'
                files = [(field, (f'reference_{i + 1:02d}.png', raw, 'image/png')) for i, raw in enumerate(payloads)]
                if mask_bytes:
                    files.append(('mask', ('mask.png', mask_bytes, 'image/png')))
                resp = requests.post(f'{api_base_url}/{endpoint}', headers=headers, data=request, files=files, timeout=(20, 300), allow_redirects=False)
            else:
                resp = requests.post(f'{api_base_url}/{endpoint}', headers=headers, json=request, timeout=(20, 300), allow_redirects=False)
        except requests.RequestException as exc:
            _log_request('error', request, len(payloads), error=type(exc).__name__, request_hash=request_hash, elapsed_seconds=round(time.perf_counter() - started, 3), api_base_url=api_base_url)
            raise RuntimeError('请求中断，未自动重试。服务端可能已生成，请核对用量后再手动重试。') from None
        request_id = resp.headers.get('x-request-id', '')
        elapsed_seconds = round(time.perf_counter() - started, 3)
        if resp.status_code != 200:
            try:
                error = resp.json().get('error', {})
                message = str(error.get('message', '请求失败')).replace(key, '[redacted]')[:400]
            except (ValueError, AttributeError):
                message = '响应不是标准错误格式'
            _log_request('error', request, len(payloads), http_status=resp.status_code, error=message, request_id=request_id, request_hash=request_hash, elapsed_seconds=elapsed_seconds, api_base_url=api_base_url)
            raise RuntimeError(f'图像 API {resp.status_code}: {message}；request_id={request_id}。未自动切换接口、模型或重试。')
        usage = None
        try:
            data = resp.json()
            usage = data.get('usage') or {}
            results = []
            for item in data.get('data', []):
                if item.get('b64_json'):
                    encoded = item['b64_json']
                    if encoded.startswith('data:image/'):
                        encoded = encoded.split(',', 1)[1]
                    raw = base64.b64decode(encoded, validate=True)
                elif item.get('url'):
                    raw = download_image(item['url'])
                else:
                    raise ValueError('响应没有 b64_json 或图片 URL')
                _decode_image(raw)
                results.append(raw)
            if len(results) != request['n']:
                raise ValueError('返回图片数量与请求不一致')
        except (ValueError, TypeError, KeyError, AttributeError, OSError, requests.RequestException, RuntimeError) as exc:
            message = f'返回图片读取失败 ({type(exc).__name__})；服务端可能已经计费，未重新生图。'
            _log_request('error', request, len(payloads), usage=usage, http_status=200, error=message, request_id=request_id, request_hash=request_hash, elapsed_seconds=elapsed_seconds, api_base_url=api_base_url)
            raise RuntimeError(message) from None
        _log_request('ok', request, len(payloads), usage=usage, http_status=200, request_id=request_id, request_hash=request_hash, elapsed_seconds=elapsed_seconds, api_base_url=api_base_url)
        return (results, dict(manifest=manifest, request_hash=request_hash, usage=usage, request_id=request_id, endpoint=endpoint, elapsed_seconds=elapsed_seconds, created_at=datetime.datetime.now().isoformat(timespec='seconds')))
